export const ACTION_TYPE = {
  // Questions Type
  GET_AllQUESTIONS_LIST_REQUEST: "GET_AllQUESTIONS_LIST_REQUEST",
  GET_AllQUESTIONS_LIST_SUCCESS: "GET_AllQUESTIONS_LIST_SUCCESS",
  GET_AllQUESTIONS_LIST_FAILURE: "GET_AllQUESTIONS_LIST_FAILURE",

  // Submit Type
  POST_SUBMIT_ANSWER_REQUEST: "POST_SUBMIT_ANSWER_REQUEST",
  POST_SUBMIT_ANSWER_SUCCESS: "POST_SUBMIT_ANSWER_SUCCESS",
  POST_SUBMIT_ANSWER_FAILURE: "POST_SUBMIT_ANSWER_FAILURE",

  // User LogOut
  LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",
};
